import { withGeneratedCombatRulesFacts } from "./combatRulesFacts";
import type { Locale, RulePageCopy } from "./types";

const rawCombatRulesContent: Record<Locale, RulePageCopy> = {
  ru: {
    eyebrow: "Combat Codex",
    title: "Библиотека правил боевой системы",
    lead:
      "Это короткое и читаемое описание текущей боевой системы в коде: порядок раунда, влияние статов, предметов, типов урона, зональной брони, ресурсов, эффектов и предметных навыков.",
    openSandbox: "Открыть Combat Sandbox",
    backToMenu: "Назад в Menu",
    contentsTitle: "Содержание",
    contents: [
      { id: "round", label: "Как проходит раунд" },
      { id: "stats", label: "Статы и формулы" },
      { id: "items", label: "Предметы и экипировка" },
      { id: "skills", label: "Скиллы от предметов" },
      { id: "damage", label: "Типы урона" },
      { id: "armor", label: "Броня и пробитие" },
      { id: "zones", label: "Зоны и множители" },
      { id: "resources", label: "Боевые ресурсы" },
      { id: "example", label: "Пример расчета" },
      { id: "tips", label: "Практические советы" },
    ],
    sections: [
      {
        id: "round",
        title: "Как проходит раунд",
        intro: "Каждый раунд это короткая последовательность проверок с понятным порядком и тиками активных эффектов.",
        bullets: [
          "Перед боем для игрока и бота собирается боевой снимок: готовый набор боевых чисел из статов и экипировки.",
          "Игрок выбирает 1 зону атаки и ровно 2 зоны защиты.",
          "Кто ходит первым, решает agility. При равенстве порядок определяется случайно.",
          "В начале хода срабатывают активные эффекты: лечение, урон по времени и потеря или восстановление ресурсов.",
          "Состояния вроде Exposed и Staggered тоже живут в тайминге активных эффектов, поэтому их окно зависит от того, кто ходит следующим.",
          "Дальше движок проверяет уклонение, затем блок или пробитие, затем критический удар, затем итоговый урон.",
          "Расходник может либо заменить атаку, либо сработать вместе с ней, если у предмета режим with_attack.",
          "После этого обновляются HP, ресурсы, активные эффекты и боевой журнал. При 0 HP бой заканчивается.",
        ],
        callouts: [
          { label: "Атака", value: "1 зона" },
          { label: "Защита", value: "2 зоны" },
          { label: "Порядок хода", value: "По AGI", tone: "agility" },
          { label: "Тик эффектов", value: "Статусы срабатывают до удара", tone: "armor" },
        ],
        steps: [
          "1. Собирается боевой снимок из статов и экипировки.",
          "2. Обе стороны выбирают атаку, защитные зоны и при желании навык или расходник.",
          "3. По AGI определяется порядок хода.",
          "4. В начале своего хода боец сначала разрешает тики активных эффектов.",
          "5. Для каждой атаки проходят уклонение, броня, блок или пробитие, критический удар и финальный урон.",
          "6. Обновляются HP, ресурсы, активные эффекты и боевой журнал.",
        ],
      },
      {
        id: "stats",
        title: "Статы и формулы",
        intro: "Базовые статы напрямую превращаются в боевые шансы, урон и выживаемость.",
        bullets: [
          "Strength увеличивает базовый урон и шанс пробить блок.",
          "Agility повышает уклонение и влияет на порядок хода.",
          "Rage повышает шанс крита и силу критического удара.",
          "Endurance увеличивает максимум HP и повышает шанс на сильный бросок блока.",
        ],
        callouts: [
          { label: "Base Damage", value: "8 + STR * 1.2", tone: "strength" },
          { label: "Base Dodge", value: "5 + AGI * 2, cap 45%", tone: "agility" },
          { label: "Base Crit", value: "3 + RAGE * 3, cap 40%", tone: "rage" },
          { label: "Max HP", value: "100 + END * 8", tone: "armor" },
          { label: "Crit Multiplier", value: "1.35 + RAGE * 0.03 + END * 0.01", tone: "rage" },
          { label: "Block Penetration", value: "20 + STR * 3, minus enemy STR * 2, cap 80%", tone: "strength" },
          { label: "Бросок блока", value: "40-70% снижения; высокая END чаще дает сильный блок", tone: "armor" },
        ],
      },
      {
        id: "items",
        title: "Предметы и экипировка",
        intro: "Предметы здесь не косметика. Они реально собирают боевой профиль персонажа.",
        bullets: [
          "Оружие задает тип урона, пробитие и дополнительные боевые бонусы.",
          "Части брони дают отдельные значения защиты по slash, pierce, blunt и chop, плюс вклад в защиту зон.",
          "Щит добавляет силу блока и защитную полезность.",
          "Двуручное оружие занимает основную руку как two-hand gear и убирает синергию со щитом во второй руке.",
          "Броня, перчатки, обувь и аксессуары тоже могут открывать навыки, а не только оружие.",
          "В Builder игрок вручную собирает набор из максимум 5 активных кнопок из общего пула открытых навыков.",
          "Расходники берутся из инвентаря. Одни заменяют атаку в раунде, другие накладывают длительные эффекты вроде Regeneration.",
        ],
        callouts: [
          { label: "Sword", value: "Режущее оружие", tone: "strength" },
          { label: "Dagger", value: "Быстрое колющее оружие", tone: "agility" },
          { label: "Mace", value: "Дробящее давление и guard-линия", tone: "strength" },
          { label: "Axe", value: "Рубящее давление и атака по нижним зонам", tone: "strength" },
          { label: "Shield", value: "Броня и сила блока", tone: "armor" },
          { label: "Greatsword", value: "Тяжелый двуручный урон", tone: "strength" },
        ],
        table: {
          columns: ["Предмет", "Профиль урона", "Пробитие", "Навык и цена"],
          rows: [],
        },
      },
      {
        id: "skills",
        title: "Скиллы от предметов",
        intro:
          "Система навыков завязана на экипировке. Навык здесь это не отдельное заклинание, а усиленная атака или полезное действие от предмета.",
        bullets: [
          "Оружие может открывать уникальные атаки и боевые полезные эффекты.",
          "Разные классы оружия меняют твой набор кнопок и рисунок размена.",
          "Броня и аксессуары тоже могут давать собственные навыки и полезные эффекты.",
          "Защитная экипировка чаще открывает sustain, control и utility-линии.",
          "Тяжелое оружие обычно двигает бой в сторону давления и тяжелых атак.",
          "Игрок видит полный пул открытых навыков, но в боевой панели держит только 5 выбранных кнопок.",
          "Любой навык тратит ресурс. Если нужного ресурса меньше стоимости, использовать его нельзя.",
          "Каждый навык тратит ресурс, усиливает текущий профиль атаки и может добавить шанс крита или пробитие.",
          "Часть навыков накладывает timed effects: bleed, stagger, короткие окна защиты и другие усиления или ослабления.",
          "Новые setup/payoff навыки создают именованные окна: Exposed делает цель удобнее для наказания, а Staggered ослабляет ее block и dodge на следующий размен.",
          "Это значит, что часть кнопок лучше работает как подготовка, а часть как добивание. Порядок нажатий здесь важен.",
          "Навык все равно наносит урон через обычную боевую формулу, а не обходит ее.",
          "То есть набор навыков определяет не только числа, но и реальный набор боевых кнопок.",
        ],
        callouts: [],
      },
      {
        id: "damage",
        title: "Типы урона",
        intro: "Урон в системе не одна плоская цифра. Каждый удар работает через свой damage profile.",
        bullets: [
          "Slash это широкое режущее давление. Сейчас его главные носители это sword и greatsword.",
          "Pierce это точечный урон с хорошей синергией с критами и пробитием. В ранней мете это прежде всего dagger.",
          "Blunt это ударный урон. В текущем наборе он приходит через mace line, shield effects и запасные профили.",
          "Chop это тяжелый рубящий профиль. Код его полностью поддерживает, и сейчас он живет в axe line.",
          "Важно: итог не считается одной цифрой заранее. Он решается отдельно по slash, pierce, blunt и chop.",
          "После этого выжившие куски складываются в финальный урон.",
          "Текущий профиль атаки собирается так: 60% от базового урона оружия и 40% от стилевого профиля класса оружия для выбранной зоны.",
        ],
        callouts: [
          { label: "Slash", value: "Широкое давление", tone: "slash" },
          { label: "Pierce", value: "Точность и пробитие", tone: "pierce" },
          { label: "Blunt", value: "Удар и давление на guard", tone: "blunt" },
          { label: "Chop", value: "Тяжелый рубящий профиль", tone: "chop" },
          { label: "Правило урона", value: "Каждый тип урона режется своей частью брони отдельно", tone: "armor" },
          { label: "Финальный урон", value: "Выжившие slash, pierce, blunt и chop складываются в итог", tone: "strength" },
        ],
        steps: [
          "1. Берется базовый урон оружия.",
          "2. Читается стилевой профиль класса оружия для выбранной зоны.",
          "3. Эти два профиля смешиваются как 60% + 40%.",
          "4. Сверху накладываются множитель зоны, бонус навыка и критический удар.",
          "5. Каждый тип урона отдельно режется соответствующей броней.",
        ],
      },
      {
        id: "armor",
        title: "Броня и пробитие",
        intro: "Броня и пробитие работают как отдельный слой расчета после попадания по защищенной зоне.",
        bullets: [
          "Броня хранится по 4 профилям: slash, pierce, blunt и chop.",
          "Если зона прикрыта, удар может быть заблокирован или частично продавлен пробитием.",
          "Пробитие приходит из оружия, бонусов предметов и предметных навыков.",
          "Щиты и броня меняют защитный профиль даже без активного использования навыка.",
          "Формула по типу урона такая: effectiveArmor = armor - flatPen - armor * percentPen / 100.",
          "После этого итог по типу считается как max(0, attackValue - effectiveArmor).",
          "Если проверка пробития не проходит, блок режет оставшийся урон роллом в диапазоне 40-70%. Высокая Endurance повышает шанс на сильный блок.",
        ],
        callouts: [
          { label: "Armor", value: "4 раздельных профиля", tone: "armor" },
          { label: "Пробитие", value: "Частично обходит защиту", tone: "strength" },
          { label: "Shield", value: "Дает armor и block power", tone: "armor" },
          { label: "Броня зоны", value: "Защищенная зона получает усиленный профиль брони", tone: "armor" },
          { label: "Бросок блока", value: "40-70% снижения после провала проверки пробития", tone: "armor" },
          { label: "Проверка пролома", value: "STR против STR, затем бонусы пробития и вражеский block bonus, cap 95%", tone: "strength" },
        ],
        steps: [
          "1. Смотрим, прикрыта ли атакуемая зона защитой.",
          "2. Если да, зона получает усиленный профиль брони через веса экипировки по слотам.",
          "3. Из этой брони вычитается плоское пробитие и процентное пробитие по каждому типу урона.",
          "4. Если проверка пробития не прошла, оставшийся урон дополнительно режется броском блока.",
          "5. Что останется после этих шагов, идет в финальный урон.",
        ],
      },
      {
        id: "zones",
        title: "Зоны и множители",
        intro: "Выбор зоны влияет и на урон, и на защиту. Это один из самых важных скрытых слоев системы.",
        bullets: [
          "Множитель зоны для атаки: head x1.2, chest x1.1, belly x1.0, waist x0.9, legs x0.8.",
          "Если зона защищена, игра усиливает броню этой зоны через armorBySlot и специальные веса слотов.",
          "Head сильнее опирается на helmet и вторую руку, chest на armor и вторую руку, legs на boots.",
          "Даже базовая защита у зон разная: например chest лучше держит blunt, а legs хуже держат pierce.",
        ],
        callouts: [
          { label: "Head", value: "x1.2 урона", tone: "slash" },
          { label: "Chest", value: "x1.1 урона", tone: "pierce" },
          { label: "Belly", value: "x1.0 урона", tone: "strength" },
          { label: "Waist", value: "x0.9 урона", tone: "agility" },
          { label: "Legs", value: "x0.8 урона", tone: "armor" },
          { label: "Защита зоны", value: "Прикрытая зона получает усиленный профиль брони", tone: "armor" },
        ],
      },
      {
        id: "resources",
        title: "Боевые ресурсы",
        intro: "Ресурсы управляют тем, какие сильные действия ты можешь позволить себе в следующем раунде.",
        bullets: [
          "Momentum это основное атакующее топливо, и оно копится на чистых попаданиях и части продавленных ударов.",
          "Guard это защитное топливо, особенно для shield line, и оно растет на успешных блоках.",
          "Focus связан с точностью и техническими действиями. В текущем коде он растет после успешного уклонения.",
          "Rage связан с тяжелыми и критовыми решениями. В текущем коде он растет после критических попаданий.",
          "Setup/payoff циклы важны и здесь: часто один ход уходит на создание Exposed или Staggered, а следующий ресурсный навык становится payoff-ударом.",
          "Все ресурсы ограничены потолком 100, а расходники и timed effects тоже могут восстанавливать или сжигать их по тикам.",
        ],
        callouts: [
          { label: "Momentum", value: "+12 on clean hit, +8 on penetration", tone: "strength" },
          { label: "Guard", value: "+8 on block", tone: "armor" },
          { label: "Focus", value: "+10 on dodge", tone: "agility" },
          { label: "Rage", value: "+14 on crit", tone: "rage" },
          { label: "Тик эффектов", value: "Может лечить HP или сжигать Guard / Focus каждый ход", tone: "armor" },
        ],
      },
      {
        id: "example",
        title: "Пример расчета",
        intro: "Ниже упрощенный пример того, как игра считает один удар мечом в защищенную chest-zone врага в броне.",
        bullets: [
          "Берется базовый профиль меча, затем к нему домешивается стилевой профиль выбранной зоны.",
          "Для chest работает множитель зоны x1.1, поэтому профиль атаки сначала немного растет.",
          "Если зона прикрыта, в работу вступают броня chest-zone, броня корпуса и возможный блок второй рукой.",
          "Дальше по slash и pierce отдельно вычитается броня, затем проверяются пробитие, блок и критический удар.",
          "В финальный урон идет только тот остаток, который пережил все эти шаги.",
        ],
        steps: [
          "1. Меч формирует slash/pierce profile.",
          "2. Chest дает x1.1 к атаке.",
          "3. Броня режет slash и pierce по отдельности.",
          "4. Пробитие частично обходит броню, а блок может срезать остаток.",
          "5. Критический удар домножает surviving profile, затем считается финальный урон.",
        ],
        callouts: [
          { label: "Оружие", value: "Профиль меча: смесь slash / pierce", tone: "strength" },
          { label: "Зона", value: "Chest: x1.1 урона", tone: "pierce" },
          { label: "Броня", value: "Профиль брони по типам урона", tone: "armor" },
          { label: "Вывод", value: "Slash-heavy удары лучше заходят туда, где слабее slash armor и хуже block", tone: "strength" },
        ],
      },
      {
        id: "tips",
        title: "Практические советы",
        intro: "Если читать систему как игрок, вот что важно помнить в первую очередь.",
        bullets: [
          "Без экипированного оружия ты теряешь оружейную линию навыков.",
          "Собирай не просто сильные навыки, а 5 активных кнопок с разной ценой по ресурсам, иначе часть панели будет мертвой.",
          "Плохие зоны защиты резко снижают шанс на успешный блок.",
          "Двуручное оружие дает силу, но ломает щитовую синергию.",
          "Смотреть нужно не только на урон, но и на профиль брони противника.",
          "Следи за статусами над HP: это реальные усиления и ослабления, а не просто косметические метки.",
          "Если видишь на враге Exposed или Staggered, считай это настоящим окном и успей вложить payoff-навык до истечения эффекта.",
          "Иногда расходник в нужный раунд полезнее, чем еще одна обычная атака. Regen Potion теперь это 5-ходовый эффект, а не мгновенный хил.",
          "Боевой журнал показывает тики лечения, спад эффектов и полные блоки как отдельные читаемые события.",
        ],
      },
    ],
  },
  en: {
    eyebrow: "Combat Codex",
    title: "Combat system rules library",
    lead:
      "This is a short readable guide to the current combat implementation: round order, stats, items, damage types, zone armor, resources, timed effects and item-based skills.",
    openSandbox: "Open Combat Sandbox",
    backToMenu: "Back to Menu",
    contentsTitle: "Contents",
    contents: [
      { id: "round", label: "How a round works" },
      { id: "stats", label: "Stats and formulas" },
      { id: "items", label: "Items and equipment" },
      { id: "skills", label: "Skills from items" },
      { id: "damage", label: "Damage types" },
      { id: "armor", label: "Armor and penetration" },
      { id: "zones", label: "Zones and multipliers" },
      { id: "resources", label: "Combat resources" },
      { id: "example", label: "Damage example" },
      { id: "tips", label: "Practical tips" },
    ],
    sections: [
      {
        id: "round",
        title: "How a round works",
        intro: "Each round is a short sequence of checks with a clear order and timed-effect ticks.",
        bullets: [
          "Before combat starts, the game builds one combat snapshot for the player and one for the bot.",
          "The player chooses 1 attack zone and exactly 2 defense zones.",
          "Agility decides who acts first. If agility is equal, the order is random.",
          "At the start of a turn, active effects may tick for healing, damage over time, and resource drain or restore.",
          "Named setup states such as Exposed and Staggered also live inside this active-effect timing, so their payoff windows depend on who acts next.",
          "The engine checks dodge, then block or penetration, then crit, then final damage.",
          "A consumable can replace the attack or resolve together with it if its usage mode is with_attack.",
          "After that, HP, resources, active effects and battle log are updated. At 0 HP, combat ends.",
        ],
        callouts: [
          { label: "Attack", value: "1 zone" },
          { label: "Defense", value: "2 zones" },
          { label: "Turn Order", value: "By AGI", tone: "agility" },
          { label: "Effect Tick", value: "Status ticks resolve before the hit", tone: "armor" },
        ],
        steps: [
          "1. A combat snapshot is built from stats and equipped items.",
          "2. Both sides choose attack, defense zones and optionally a skill or consumable.",
          "3. Turn order is decided by AGI.",
          "4. At the start of each acting turn, that fighter resolves active effect ticks first.",
          "5. Each attack runs through dodge, armor, block or penetration, crit and final damage.",
          "6. HP, resources, active effects and battle log are updated.",
        ],
      },
      {
        id: "stats",
        title: "Stats and formulas",
        intro: "Base stats directly become combat chances, damage and survivability.",
        bullets: [
          "Strength increases base damage and block penetration.",
          "Agility increases dodge and affects turn order.",
          "Rage increases crit chance and crit multiplier.",
          "Endurance increases max HP and raises the chance of stronger block rolls.",
        ],
        callouts: [
          { label: "Base Damage", value: "8 + STR * 1.2", tone: "strength" },
          { label: "Base Dodge", value: "5 + AGI * 2, cap 45%", tone: "agility" },
          { label: "Base Crit", value: "3 + RAGE * 3, cap 40%", tone: "rage" },
          { label: "Max HP", value: "100 + END * 8", tone: "armor" },
          { label: "Crit Multiplier", value: "1.35 + RAGE * 0.03 + END * 0.01", tone: "rage" },
          { label: "Block Penetration", value: "20 + STR * 3, minus enemy STR * 2, cap 80%", tone: "strength" },
          { label: "Block Roll", value: "40-70% reduction; higher Endurance makes strong blocks more likely", tone: "armor" },
        ],
      },
      {
        id: "items",
        title: "Items and equipment",
        intro: "Items are not cosmetic here. They build the actual combat profile of the character.",
        bullets: [
          "Weapons define damage type, penetration and extra combat bonuses.",
          "Armor pieces provide separate defense values for slash, pierce, blunt and chop, plus zone-defense contribution.",
          "A shield adds block power and defensive utility.",
          "A two-hand weapon occupies main hand as two-hand gear and removes off-hand shield synergy.",
          "Armor, gloves, boots and accessories can now unlock skills too, not just weapons.",
          "In Builder, the player manually assembles a loadout of up to 5 active skills from the full unlocked pool.",
          "Consumables come from inventory. Some replace the attack for the round, while others apply lasting effects such as Regeneration.",
        ],
        callouts: [
          { label: "Sword", value: "Slash weapon", tone: "strength" },
          { label: "Dagger", value: "Fast pierce weapon", tone: "agility" },
          { label: "Mace", value: "Blunt pressure + guard line", tone: "strength" },
          { label: "Axe", value: "Chop pressure + low-line punish", tone: "strength" },
          { label: "Shield", value: "Armor + block power", tone: "armor" },
          { label: "Greatsword", value: "Two-hand heavy damage", tone: "strength" },
        ],
        table: {
          columns: ["Item", "Damage profile", "Penetration", "Skill and cost"],
          rows: [],
        },
      },
      {
        id: "skills",
        title: "Skills from items",
        intro: "The skill system is tied to equipment. A skill here is not a spell, it is a modified attack or utility action granted by gear.",
        bullets: [
          "Weapons can unlock unique attacks and combat utilities.",
          "Different weapon classes reshape your available buttons and exchange pattern.",
          "Armor pieces and accessories can also grant their own skills and utility effects.",
          "Defensive gear can unlock control, sustain, or utility skills.",
          "Heavy weapons usually push the fight toward pressure and high-impact attacks.",
          "The player can see the full unlocked pool, but only 5 selected skills can stay on the live combat bar.",
          "Every skill requires a resource. If you do not have enough of that resource, the skill cannot be used.",
          "Each skill spends a resource, multiplies the current attack profile, and may add crit chance or penetration.",
          "Some skills also apply timed effects such as bleed, stagger, short defensive windows and other buffs or debuffs.",
          "The newer setup/payoff skills now create named windows: Exposed makes the target easier to punish, while Staggered weakens block and dodge for the follow-up exchange.",
          "That means some buttons are openers and others are finishers. Exposed and Staggered windows amplify later attacks, so sequencing matters.",
          "So yes, skills do deal damage, but through the same normal combat formula instead of bypassing it.",
          "This means loadout changes both your numbers and your available combat buttons.",
        ],
        callouts: [],
      },
      {
        id: "damage",
        title: "Damage types",
        intro: "Combat damage is not one flat number. Each hit works through a damage profile.",
        bullets: [
          "Slash is broad cutting pressure. Right now its main carriers are sword and greatsword.",
          "Pierce is focused damage with strong crit and penetration synergy. In the early meta that means dagger first.",
          "Blunt is impact damage. In the current set it appears through the mace line, shield effects and fallback profiles.",
          "Chop is a heavy edge profile. The code fully supports it, and the current set uses it through the axe line.",
          "Important: the outcome is not calculated as one number first. It is resolved separately for slash, pierce, blunt and chop.",
          "After that, the surviving pieces are summed into final damage.",
          "The current attack profile is built like this: 60% from weapon baseDamage and 40% from the selected zone style profile of the weapon class.",
        ],
        callouts: [
          { label: "Slash", value: "Broad pressure", tone: "slash" },
          { label: "Pierce", value: "Precision and penetration", tone: "pierce" },
          { label: "Blunt", value: "Impact and guard pressure", tone: "blunt" },
          { label: "Chop", value: "Heavy edge profile", tone: "chop" },
          { label: "Damage Rule", value: "Each damage type is mitigated by its matching armor slice separately", tone: "armor" },
          { label: "Final Damage", value: "The surviving slash, pierce, blunt and chop values are added together", tone: "strength" },
        ],
        steps: [
          "1. Start with the weapon base damage.",
          "2. Read the weapon-class style profile for the selected zone.",
          "3. Mix those two profiles as 60% + 40%.",
          "4. Apply zone multiplier, skill bonus and crit.",
          "5. Mitigate each damage type with its matching armor.",
        ],
      },
      {
        id: "armor",
        title: "Armor and penetration",
        intro: "Armor and penetration are a separate calculation layer after a hit reaches a defended zone.",
        bullets: [
          "Armor is stored in 4 separate profiles: slash, pierce, blunt and chop.",
          "If the zone is covered, the hit may be blocked or partly forced through with penetration.",
          "Penetration comes from weapons, item bonuses and item-based skills.",
          "Shields and armor pieces change defense profiles even before any active skill is used.",
          "Per damage type, the formula is: effectiveArmor = armor - flatPen - armor * percentPen / 100.",
          "After that, each type becomes max(0, attackValue - effectiveArmor).",
          "If the penetration check fails, block reduces the remaining damage with a 40-70% roll. Higher Endurance makes strong blocks more likely.",
        ],
        callouts: [
          { label: "Armor", value: "4 separate profiles", tone: "armor" },
          { label: "Penetration", value: "Partly bypasses defense", tone: "strength" },
          { label: "Shield", value: "Adds armor and block power", tone: "armor" },
          { label: "Zone Armor", value: "A defended zone gets an upgraded armor profile", tone: "armor" },
          { label: "Block Roll", value: "40-70% reduction after a failed penetration check", tone: "armor" },
          { label: "Guard-Break Check", value: "STR vs STR, then penetration bonuses and enemy block bonus, cap 95%", tone: "strength" },
        ],
        steps: [
          "1. Check whether the attacked zone is covered by defense.",
          "2. If it is, that zone gets an upgraded armor profile through equipment slot weights.",
          "3. Subtract flat penetration and percentage penetration from that armor for each damage type.",
          "4. If the penetration check fails, block further cuts the remaining damage.",
          "5. Whatever survives these steps becomes final damage.",
        ],
      },
      {
        id: "zones",
        title: "Zones and multipliers",
        intro: "Zone choice changes both damage and defense. It is one of the most important hidden layers of the system.",
        bullets: [
          "Zone modifier for attacks: head x1.2, chest x1.1, belly x1.0, waist x0.9, legs x0.8.",
          "If the zone is defended, the game boosts that zone with armorBySlot and dedicated slot weights.",
          "Head leans more on helmet and off-hand, chest on armor and off-hand, legs on boots.",
          "Even the generic defense layer differs per zone: for example chest handles blunt better, while legs are weaker against pierce.",
        ],
        callouts: [
          { label: "Head", value: "x1.2 damage", tone: "slash" },
          { label: "Chest", value: "x1.1 damage", tone: "pierce" },
          { label: "Belly", value: "x1.0 damage", tone: "strength" },
          { label: "Waist", value: "x0.9 damage", tone: "agility" },
          { label: "Legs", value: "x0.8 damage", tone: "armor" },
          { label: "Zone Defense", value: "A defended zone gets an upgraded armor profile", tone: "armor" },
        ],
      },
      {
        id: "resources",
        title: "Combat resources",
        intro: "Resources decide which stronger actions you can afford in the next round.",
        bullets: [
          "Momentum is the main offensive fuel and it builds on clean hits and some penetrations.",
          "Guard is the defensive fuel, especially for shield actions, and it builds on successful blocks.",
          "Focus supports precise and technical actions. In the current code it builds after successful dodges.",
          "Rage is tied to heavier commitments and crit-oriented play. In the current code it builds after crits.",
          "Setup/payoff loops matter here too: you often spend one round creating Exposed or Staggered, then spend the next affordable skill on the payoff hit.",
          "All resources are capped at 100, and consumables or timed effects can also restore or drain them over time.",
        ],
        callouts: [
          { label: "Momentum", value: "+12 on clean hit, +8 on penetration", tone: "strength" },
          { label: "Guard", value: "+8 on block", tone: "armor" },
          { label: "Focus", value: "+10 on dodge", tone: "agility" },
          { label: "Rage", value: "+14 on crit", tone: "rage" },
          { label: "Effect Tick", value: "Can heal HP or drain Guard / Focus each turn", tone: "armor" },
        ],
      },
      {
        id: "example",
        title: "Damage example",
        intro: "This is a simplified example of how the game thinks about one sword hit into a defended chest zone with armor.",
        bullets: [
          "Start from the sword base profile, then mix in the selected zone style profile.",
          "Chest uses the x1.1 zone modifier, so the attack profile grows slightly before mitigation.",
          "If the zone is covered, chest-zone armor, torso armor and possible off-hand block all matter.",
          "Then slash and pierce are reduced separately by armor, then penetration, block and crit are checked.",
          "Only the remaining profile becomes final damage.",
        ],
        steps: [
          "1. The sword creates a slash/pierce profile.",
          "2. Chest adds x1.1 damage.",
          "3. Armor mitigates slash and pierce separately.",
          "4. Penetration partly bypasses armor, and block may cut the rest.",
          "5. Crit multiplies the surviving profile, then final damage is summed.",
        ],
        callouts: [
          { label: "Weapon", value: "Sword profile: slash / pierce mix", tone: "strength" },
          { label: "Zone", value: "Chest: x1.1 damage", tone: "pierce" },
          { label: "Armor", value: "Armor profile by damage type", tone: "armor" },
          { label: "Takeaway", value: "Slash-heavy hits work best where slash armor and block are weaker", tone: "strength" },
        ],
      },
      {
        id: "tips",
        title: "Practical tips",
        intro: "If you read the system like a player, these are the main things to remember.",
        bullets: [
          "Without an equipped weapon, you lose the weapon-based skill line.",
          "Do not just stack strong skills. Build a 5-button panel with different resource costs so it stays usable.",
          "Bad defense zone choices sharply reduce your chance to block.",
          "Two-hand weapons give power but remove shield synergy.",
          "Look at the enemy armor profile, not just your raw damage.",
          "Watch the status row above HP. Those are live buffs and debuffs, not cosmetic labels.",
          "If you see Exposed or Staggered on the enemy, treat that as a real combat window and spend your stronger payoff skill before it expires.",
          "Sometimes a consumable in the right round is better than one more basic hit. Regen Potion is now a 5-turn effect, not just a one-shot heal.",
          "The battle log now surfaces healing ticks, effect expiration and full blocks as separate readable outcomes.",
        ],
      },
    ],
  },
};

export const combatRulesContent: Record<Locale, RulePageCopy> = {
  ru: {
    ...rawCombatRulesContent.ru,
    sections: withGeneratedCombatRulesFacts(rawCombatRulesContent.ru.sections, "ru"),
  },
  en: {
    ...rawCombatRulesContent.en,
    sections: withGeneratedCombatRulesFacts(rawCombatRulesContent.en.sections, "en"),
  },
};
