import { withGeneratedCombatRulesFacts } from "./combatRulesFacts";
import type { Locale, RulePageCopy } from "./types";

const rawCombatRulesContent: Record<Locale, RulePageCopy> = {
  ru: {
    eyebrow: "Combat Codex",
    title: "Библиотека правил боевой системы",
    lead:
      "Это краткое и читаемое описание того, как работает текущая боевая система в коде: порядок раунда, влияние статов, предметов, типов урона, брони, ресурсов, эффектов и предметных скиллов.",
    openSandbox: "Открыть Combat Sandbox",
    backToMenu: "Назад в Menu",
    contentsTitle: "Содержание",
    contents: [
      { id: "round", label: "Как проходит раунд" },
      { id: "stats", label: "Статы и формулы" },
      { id: "items", label: "Предметы и экипировка" },
      { id: "skills", label: "Скиллы от предметов" },
      { id: "damage", label: "Типы урона" },
      { id: "armor", label: "Броня и penetration" },
      { id: "zones", label: "Зоны и множители" },
      { id: "resources", label: "Боевые ресурсы" },
      { id: "example", label: "Пример расчёта" },
      { id: "tips", label: "Практические советы" },
    ],
    sections: [
      {
        id: "round",
        title: "Как проходит раунд",
        intro: "Каждый раунд в игре это один короткий цикл проверок с понятным порядком и тиками активных эффектов.",
        bullets: [
          "Перед боем для игрока и бота собирается combat snapshot: готовый набор боевых чисел из статов и предметов.",
          "Игрок выбирает 1 зону атаки и ровно 2 зоны защиты.",
          "Кто ходит первым, решает agility. При равенстве порядок определяется случайно.",
          "В начале хода срабатывают active effects: лечение, урон по времени и drain или restore ресурсов.",
          "Дальше движок проверяет dodge, затем block или penetration, затем crit, затем итоговый урон.",
          "Consumable может либо заменить атаку, либо сработать вместе с ней, если у предмета режим with_attack.",
          "После этого обновляются HP, ресурсы, active effects и battle log. При 0 HP бой заканчивается.",
        ],
        callouts: [
          { label: "Атака", value: "1 зона" },
          { label: "Защита", value: "2 зоны" },
          { label: "Порядок хода", value: "По AGI", tone: "agility" },
          { label: "Effect Tick", value: "Сначала тики статусов, потом удар", tone: "armor" },
        ],
        steps: [
          "1. Собирается combat snapshot из статов и экипировки.",
          "2. Игроки выбирают атаку, защитные зоны и при желании skill или consumable.",
          "3. По AGI определяется порядок хода.",
          "4. В начале своего хода боец сначала разрешает тики активных эффектов.",
          "5. Для каждой атаки проходят dodge, armor, block или penetration, crit и финальный урон.",
          "6. Обновляются HP, ресурсы, active effects и battle log.",
        ],
      },
      {
        id: "stats",
        title: "Статы и формулы",
        intro: "Базовые статы напрямую превращаются в боевые шансы, урон и выживаемость.",
        bullets: [
          "Strength увеличивает базовый урон и block penetration.",
          "Agility повышает dodge и влияет на порядок хода.",
          "Rage повышает базовый crit chance.",
          "Endurance увеличивает max HP и crit multiplier.",
        ],
        callouts: [
          { label: "Base Damage", value: "10 + STR * 1.5", tone: "strength" },
          { label: "Base Dodge", value: "5 + AGI * 2, cap 45%", tone: "agility" },
          { label: "Base Crit", value: "3 + RAGE * 3, cap 40%", tone: "rage" },
          { label: "Max HP", value: "100 + END * 10", tone: "armor" },
          { label: "Crit Multiplier", value: "1.5 + END * 0.03", tone: "armor" },
          { label: "Block Penetration", value: "20 + STR * 3, cap 75%", tone: "strength" },
        ],
      },
      {
        id: "items",
        title: "Предметы и экипировка",
        intro: "Предметы здесь важнее обычной косметики. Они реально собирают боевой профиль персонажа.",
        bullets: [
          "Оружие задаёт тип урона, penetration и дополнительные бонусы.",
          "Броня даёт профиль защиты по типам урона: slash, pierce, blunt, chop.",
          "Щит добавляет block power и отдельный defensive utility.",
          "Двуручное оружие занимает main hand как two-hand gear и убирает off-hand синергию.",
          "Предметы из брони, перчаток, обуви и аксессуаров тоже могут открывать skills, а не только оружие.",
          "В Builder игрок вручную собирает loadout из максимум 5 skill-слотов из общего пула открытых skills.",
          "Consumables берутся из инвентаря и могут либо заменить атаку, либо наложить длительный эффект вроде Regeneration.",
        ],
        callouts: [
          { label: "Sword", value: "Slash weapon", tone: "strength" },
          { label: "Dagger", value: "Fast pierce weapon", tone: "agility" },
          { label: "Mace", value: "Blunt pressure + guard line", tone: "strength" },
          { label: "Axe", value: "Chop pressure + low-line punish", tone: "strength" },
          { label: "Shield", value: "Armor + block power", tone: "armor" },
          { label: "Greatsword", value: "Two-hand heavy damage", tone: "strength" },
        ],
        table: {
          columns: ["Предмет", "Профиль урона", "Penetration", "Skill и цена"],
          rows: [],
        },
      },
      {
        id: "skills",
        title: "Скиллы от предметов",
        intro:
          "Система скиллов завязана на экипировке. Здесь skill это не отдельное заклинание, а усиленная атака или utility-действие от предмета.",
        bullets: [
          "Training Sword открывает Feint Slash.",
          "Training Dagger открывает Piercing Lunge.",
          "Leather Cap, Leather Vest, Braced Gloves, Trail Boots и аксессуары тоже дают свои skills.",
          "Oak Shield открывает Shield Bash.",
          "Great Training Sword открывает Heavy Cleave.",
          "Игрок видит полный пул открытых skills, но в боевой панели может держать только 5 выбранных кнопок.",
          "Любой skill обязательно тратит ресурс. Если нужного ресурса меньше стоимости skill, использовать его нельзя.",
          "Любой skill умножает текущий профиль атаки, может добавить crit chance и penetration.",
          "Часть skills дополнительно накладывает timed effects: bleed, stagger, short defensive windows и другие buffs или debuffs.",
          "То есть skill всё ещё наносит урон через обычную боевую формулу, а не обходит её.",
          "Это значит, что loadout определяет не только числа, но и набор доступных боевых кнопок.",
        ],
        callouts: [],
      },
      {
        id: "damage",
        title: "Типы урона",
        intro: "Урон в системе не один общий. Каждый удар работает через свой damage profile.",
        bullets: [
          "Slash это широкое режущее давление. Сейчас его основными источниками выступают sword и greatsword.",
          "Pierce это точечный урон с хорошей синергией с crit и penetration. Базовый носитель в starter set это dagger.",
          "Blunt это ударный урон. В текущем starter set он появляется в shield skill, mace line и в общих fallback-профилях.",
          "Chop это тяжёлый рубящий профиль. В коде он уже поддержан, и в starter set его ведёт axe line.",
          "Важно помнить: итог считается не одной цифрой, а отдельно по slash, pierce, blunt и chop.",
          "После этого остатки по всем типам складываются в final damage.",
          "Текущий профиль удара собирается так: 60% берётся из baseDamage оружия и 40% из style profile weapon class для выбранной зоны.",
        ],
        callouts: [
          { label: "Slash", value: "Широкое давление", tone: "slash" },
          { label: "Pierce", value: "Точность и penetration", tone: "pierce" },
          { label: "Blunt", value: "Impact и guard pressure", tone: "blunt" },
          { label: "Chop", value: "Heavy edge profile", tone: "chop" },
          { label: "Damage Rule", value: "Каждый тип урона режется своей частью брони отдельно", tone: "armor" },
          { label: "Final Damage", value: "Остатки slash, pierce, blunt и chop складываются в итог", tone: "strength" },
        ],
        steps: [
          "1. Берётся base damage оружия.",
          "2. Определяется style profile weapon class для выбранной зоны.",
          "3. Эти два профиля смешиваются как 60% + 40%.",
          "4. На профиль накладываются множители зоны, skill bonus и crit.",
          "5. Каждый тип урона отдельно режется своей бронёй.",
        ],
      },
      {
        id: "armor",
        title: "Броня и penetration",
        intro: "Броня и penetration работают как отдельный слой расчёта после попадания по защищённой зоне.",
        bullets: [
          "Броня хранится по 4 профилям: slash, pierce, blunt, chop.",
          "Если зона прикрыта, удар может быть заблокирован или частично продавлен penetration.",
          "Penetration приходит из оружия, бонусов предметов и item-based skills.",
          "Leather Vest и Oak Shield заметно меняют профиль защиты даже без активного skill usage.",
          "Формула по типу урона такая: effectiveArmor = armor - flatPen - armor * percentPen / 100.",
          "После этого итог по типу считается как max(0, attackValue - effectiveArmor).",
          "Если penetration check не проходит, блок режет уже оставшийся урон на 50% + blockPowerBonus, максимум до 90%.",
        ],
        callouts: [
          { label: "Armor", value: "4 раздельных профиля", tone: "armor" },
          { label: "Penetration", value: "Частично обходит защиту", tone: "strength" },
          { label: "Shield", value: "Даёт armor и block power", tone: "armor" },
          { label: "Oak Shield", value: "Base armor 8 / 10 / 14 / 9, +12 block power", tone: "armor" },
          { label: "Leather Vest", value: "Base armor 12 / 6 / 4 / 8", tone: "armor" },
          { label: "Guard-Break Check", value: "base pen from STR vs enemy STR, then + avg pen% - enemy block bonus, cap 95%", tone: "strength" },
        ],
        steps: [
          "1. Смотрим, прикрыта ли атакуемая зона защитой.",
          "2. Если да, зона получает усиленный armor profile через экипировку по слотам.",
          "3. Из этой брони вычитается flat penetration и процентная penetration по каждому типу урона.",
          "4. Если penetration check не прошёл, оставшийся урон дополнительно режется блоком.",
          "5. Что останется после этих шагов, идёт в final damage.",
        ],
      },
      {
        id: "zones",
        title: "Зоны и множители",
        intro: "Выбор зоны влияет и на урон, и на защиту. Это один из самых важных скрытых слоёв системы.",
        bullets: [
          "Zone modifier для атаки: head x1.2, chest x1.1, belly x1.0, waist x0.9, legs x0.8.",
          "Если зона защищена, игра усиливает броню этой зоны через armorBySlot и специальные веса слотов.",
          "Head больше опирается на helmet и off-hand, chest на armor и off-hand, legs на boots.",
          "Даже базовая generic defense у зон разная: например chest лучше держит blunt, а legs хуже держат pierce.",
        ],
        callouts: [
          { label: "Head", value: "x1.2 damage", tone: "slash" },
          { label: "Chest", value: "x1.1 damage", tone: "pierce" },
          { label: "Belly", value: "x1.0 damage", tone: "strength" },
          { label: "Waist", value: "x0.9 damage", tone: "agility" },
          { label: "Legs", value: "x0.8 damage", tone: "armor" },
          { label: "Zone Defense", value: "Прикрытая зона получает усиленный профиль брони", tone: "armor" },
        ],
      },
      {
        id: "resources",
        title: "Боевые ресурсы",
        intro: "Ресурсы управляют тем, какие сильные действия ты можешь сделать в следующем раунде.",
        bullets: [
          "Momentum это основной offensive fuel и он копится на чистых попаданиях и части продавленных ударов.",
          "Guard это defensive fuel, особенно для shield line, и он растёт на успешных блоках.",
          "Focus связан с точностью и техническими действиями. В текущем коде он растёт после успешного dodge.",
          "Rage связан с тяжёлыми и критовыми решениями. В текущем коде он растёт после crit-попаданий.",
          "Все ресурсы ограничены потолком 100, а consumables и timed effects тоже могут их восстанавливать или сжигать по тикам.",
        ],
        callouts: [
          { label: "Momentum", value: "+10 on clean hit, +8 on penetration", tone: "strength" },
          { label: "Guard", value: "+12 on block", tone: "armor" },
          { label: "Focus", value: "+10 on dodge", tone: "agility" },
          { label: "Rage", value: "+14 on crit", tone: "rage" },
          { label: "Effect Tick", value: "Может лечить HP или сжигать Guard / Focus каждый ход", tone: "armor" },
        ],
      },
      {
        id: "example",
        title: "Пример расчёта",
        intro: "Ниже упрощённый пример того, как игра мыслит один удар Training Sword по защищённой chest-zone врага в Leather Vest.",
        bullets: [
          "Берётся base profile меча: 80% slash и 20% pierce, затем к нему домешивается style profile зоны.",
          "Для chest работает zone modifier x1.1, поэтому attack profile сначала немного растёт.",
          "Если зона прикрыта, вступает в работу armor chest-zone, Leather Vest и возможный block через off-hand.",
          "Дальше по slash и pierce отдельно вычитается armor, затем проверяются penetration, block и crit.",
          "В final damage идёт только тот остаток, который пережил все эти шаги.",
        ],
        steps: [
          "1. Меч формирует slash/pierce profile.",
          "2. Chest даёт x1.1 к атаке.",
          "3. Armor режет slash и pierce по отдельности.",
          "4. Penetration частично обходит armor, block может срезать остаток.",
          "5. Crit домножает surviving profile, затем считается final damage.",
        ],
        callouts: [
          { label: "Оружие", value: "Training Sword: 80% slash / 20% pierce", tone: "strength" },
          { label: "Зона", value: "Chest: x1.1 damage", tone: "pierce" },
          { label: "Броня", value: "Leather Vest: 12 slash / 6 pierce / 4 blunt / 8 chop", tone: "armor" },
          { label: "Вывод", value: "Slash-heavy удары лучше заходят туда, где мало slash armor и нет хорошего block", tone: "strength" },
        ],
      },
      {
        id: "tips",
        title: "Практические советы",
        intro: "Если читать систему как игрок, вот что важно помнить в первую очередь.",
        bullets: [
          "Без экипированного оружия ты теряешь weapon-based skill line.",
          "Собирай не просто сильные skills, а 5 активных кнопок с разными ресурсами, иначе часть панели будет мёртвой.",
          "Неправильные зоны защиты резко снижают шанс успешного блока.",
          "Двуручное оружие даёт силу, но ломает щитовую синергию.",
          "Смотреть нужно не только на урон, но и на профиль брони противника.",
          "Следи за статусами над HP: они показывают реальные активные buffs и debuffs, а не просто косметические метки.",
          "Иногда consumable в нужный раунд полезнее, чем ещё одна обычная атака. Regen Potion это уже не мгновенный хил, а 5-ходовый эффект.",
          "Battle log теперь показывает тики лечения, спад эффектов и полный блок урона как отдельные понятные события.",
        ],
      },
    ],
  },
  en: {
    eyebrow: "Combat Codex",
    title: "Combat system rules library",
    lead:
      "This is a short readable guide to the current combat implementation: round order, stats, items, damage types, armor, resources, timed effects and item-based skills.",
    openSandbox: "Open Combat Sandbox",
    backToMenu: "Back to Menu",
    contentsTitle: "Contents",
    contents: [
      { id: "round", label: "How a round works" },
      { id: "stats", label: "Stats and formulas" },
      { id: "items", label: "Items and equipment" },
      { id: "skills", label: "Skills from items" },
      { id: "damage", label: "Damage types" },
      { id: "armor", label: "Armor and penetration" },
      { id: "zones", label: "Zones and multipliers" },
      { id: "resources", label: "Combat resources" },
      { id: "example", label: "Damage example" },
      { id: "tips", label: "Practical tips" },
    ],
    sections: [
      {
        id: "round",
        title: "How a round works",
        intro: "Each round is a short sequence of checks with a clear order and timed-effect ticks.",
        bullets: [
          "Before combat starts, the game builds one combat snapshot for the player and one for the bot.",
          "The player chooses 1 attack zone and exactly 2 defense zones.",
          "Agility decides who acts first. If agility is equal, the order is random.",
          "At the start of a turn, active effects may tick for healing, damage over time, and resource drain or restore.",
          "The engine checks dodge, then block or penetration, then crit, then final damage.",
          "A consumable can replace the attack or resolve together with it if its usage mode is with_attack.",
          "After that, HP, resources, active effects and battle log are updated. At 0 HP, combat ends.",
        ],
        callouts: [
          { label: "Attack", value: "1 zone" },
          { label: "Defense", value: "2 zones" },
          { label: "Turn Order", value: "By AGI", tone: "agility" },
          { label: "Effect Tick", value: "Status ticks resolve before the hit", tone: "armor" },
        ],
        steps: [
          "1. A combat snapshot is built from stats and equipped items.",
          "2. Both sides choose attack, defense zones and optionally a skill or consumable.",
          "3. Turn order is decided by AGI.",
          "4. At the start of each acting turn, that fighter resolves active effect ticks first.",
          "5. Each attack runs through dodge, armor, block or penetration, crit and final damage.",
          "6. HP, resources, active effects and battle log are updated.",
        ],
      },
      {
        id: "stats",
        title: "Stats and formulas",
        intro: "Base stats directly become combat chances, damage and survivability.",
        bullets: [
          "Strength increases base damage and block penetration.",
          "Agility increases dodge and affects turn order.",
          "Rage increases base crit chance.",
          "Endurance increases max HP and crit multiplier.",
        ],
        callouts: [
          { label: "Base Damage", value: "10 + STR * 1.5", tone: "strength" },
          { label: "Base Dodge", value: "5 + AGI * 2, cap 45%", tone: "agility" },
          { label: "Base Crit", value: "3 + RAGE * 3, cap 40%", tone: "rage" },
          { label: "Max HP", value: "100 + END * 10", tone: "armor" },
          { label: "Crit Multiplier", value: "1.5 + END * 0.03", tone: "armor" },
          { label: "Block Penetration", value: "20 + STR * 3, cap 75%", tone: "strength" },
        ],
      },
      {
        id: "items",
        title: "Items and equipment",
        intro: "Items are not cosmetic here. They build the actual combat profile of the character.",
        bullets: [
          "Weapons define damage type, penetration and extra combat bonuses.",
          "Armor pieces provide separate defense values for slash, pierce, blunt and chop.",
          "A shield adds block power and defensive utility.",
          "A two-hand weapon occupies main hand as two-hand gear and removes off-hand shield synergy.",
          "Armor, gloves, boots and accessories can now unlock skills too, not just weapons.",
          "In Builder, the player manually assembles a loadout of up to 5 active skills from the full unlocked pool.",
          "Consumables come from inventory. Some replace the attack for the round, while others apply lasting effects such as Regeneration.",
        ],
        callouts: [
          { label: "Sword", value: "Slash weapon", tone: "strength" },
          { label: "Dagger", value: "Fast pierce weapon", tone: "agility" },
          { label: "Mace", value: "Blunt pressure + guard line", tone: "strength" },
          { label: "Axe", value: "Chop pressure + low-line punish", tone: "strength" },
          { label: "Shield", value: "Armor + block power", tone: "armor" },
          { label: "Greatsword", value: "Two-hand heavy damage", tone: "strength" },
        ],
        table: {
          columns: ["Item", "Damage profile", "Penetration", "Skill and cost"],
          rows: [],
        },
      },
      {
        id: "skills",
        title: "Skills from items",
        intro: "The skill system is tied to equipment. A skill here is not a spell, it is a modified attack or utility action granted by gear.",
        bullets: [
          "Training Sword unlocks Feint Slash.",
          "Training Dagger unlocks Piercing Lunge.",
          "Leather Cap, Leather Vest, Braced Gloves, Trail Boots and accessories also grant their own skills.",
          "Oak Shield unlocks Shield Bash.",
          "Great Training Sword unlocks Heavy Cleave.",
          "The player can see the full unlocked pool, but only 5 selected skills can stay on the live combat bar.",
          "Every skill requires a resource. If you do not have enough of that resource, the skill cannot be used.",
          "Each skill spends a resource, multiplies the current attack profile, and may add crit chance or penetration.",
          "Some skills also apply timed effects such as bleed, stagger, short defensive windows and other buffs or debuffs.",
          "So yes, skills do deal damage, but through the same normal combat formula instead of bypassing it.",
          "This means loadout changes both your numbers and your available combat buttons.",
        ],
        callouts: [],
      },
      {
        id: "damage",
        title: "Damage types",
        intro: "Combat damage is not one flat number. Each hit works through a damage profile.",
        bullets: [
          "Slash is broad cutting pressure. Right now its main carriers are sword and greatsword.",
          "Pierce is focused damage with strong crit and penetration synergy. In the starter set that means dagger first.",
          "Blunt is impact damage. In the current starter set it appears through the shield skill, mace line and generic fallback profiles.",
          "Chop is a heavy edge profile. The code fully supports it, and the starter set now uses it through the axe line.",
          "Important: the outcome is not calculated as one number first. It is resolved separately for slash, pierce, blunt and chop.",
          "After that, the surviving pieces are summed into final damage.",
          "The current attack profile is built like this: 60% from weapon baseDamage and 40% from the selected zone style profile of the weapon class.",
        ],
        callouts: [
          { label: "Slash", value: "Broad pressure", tone: "slash" },
          { label: "Pierce", value: "Precision and penetration", tone: "pierce" },
          { label: "Blunt", value: "Impact and guard pressure", tone: "blunt" },
          { label: "Chop", value: "Heavy edge profile", tone: "chop" },
          { label: "Damage Rule", value: "Each damage type is mitigated by its matching armor slice separately", tone: "armor" },
          { label: "Final Damage", value: "The surviving slash, pierce, blunt and chop values are added together", tone: "strength" },
        ],
        steps: [
          "1. Start with the weapon base damage.",
          "2. Read the weapon-class style profile for the selected zone.",
          "3. Mix those two profiles as 60% + 40%.",
          "4. Apply zone multiplier, skill bonus and crit.",
          "5. Mitigate each damage type with its matching armor.",
        ],
      },
      {
        id: "armor",
        title: "Armor and penetration",
        intro: "Armor and penetration are a separate calculation layer after a hit reaches a defended zone.",
        bullets: [
          "Armor is stored in 4 separate profiles: slash, pierce, blunt and chop.",
          "If the zone is covered, the hit may be blocked or partly forced through with penetration.",
          "Penetration comes from weapons, item bonuses and item-based skills.",
          "Leather Vest and Oak Shield change defense profiles even before any active skill is used.",
          "Per damage type, the formula is: effectiveArmor = armor - flatPen - armor * percentPen / 100.",
          "After that, each type becomes max(0, attackValue - effectiveArmor).",
          "If the penetration check fails, block reduces the remaining damage by 50% + blockPowerBonus, capped at 90%.",
        ],
        callouts: [
          { label: "Armor", value: "4 separate profiles", tone: "armor" },
          { label: "Penetration", value: "Partly bypasses defense", tone: "strength" },
          { label: "Shield", value: "Adds armor and block power", tone: "armor" },
          { label: "Oak Shield", value: "Base armor 8 / 10 / 14 / 9, +12 block power", tone: "armor" },
          { label: "Leather Vest", value: "Base armor 12 / 6 / 4 / 8", tone: "armor" },
          { label: "Guard-Break Check", value: "base pen from STR vs enemy STR, then + avg pen% - enemy block bonus, cap 95%", tone: "strength" },
        ],
        steps: [
          "1. Check whether the attacked zone is covered by defense.",
          "2. If it is, that zone gets an upgraded armor profile through equipment slot weights.",
          "3. Subtract flat penetration and percentage penetration from that armor for each damage type.",
          "4. If the penetration check fails, block further cuts the remaining damage.",
          "5. Whatever survives these steps becomes final damage.",
        ],
      },
      {
        id: "zones",
        title: "Zones and multipliers",
        intro: "Zone choice changes both damage and defense. It is one of the most important hidden layers of the system.",
        bullets: [
          "Zone modifier for attacks: head x1.2, chest x1.1, belly x1.0, waist x0.9, legs x0.8.",
          "If the zone is defended, the game boosts that zone with armorBySlot and dedicated slot weights.",
          "Head leans more on helmet and off-hand, chest on armor and off-hand, legs on boots.",
          "Even the generic defense layer differs per zone: for example chest handles blunt better, while legs are weaker against pierce.",
        ],
        callouts: [
          { label: "Head", value: "x1.2 damage", tone: "slash" },
          { label: "Chest", value: "x1.1 damage", tone: "pierce" },
          { label: "Belly", value: "x1.0 damage", tone: "strength" },
          { label: "Waist", value: "x0.9 damage", tone: "agility" },
          { label: "Legs", value: "x0.8 damage", tone: "armor" },
          { label: "Zone Defense", value: "A defended zone gets an upgraded armor profile", tone: "armor" },
        ],
      },
      {
        id: "resources",
        title: "Combat resources",
        intro: "Resources decide which stronger actions you can afford in the next round.",
        bullets: [
          "Momentum is the main offensive fuel and it builds on clean hits and some penetrations.",
          "Guard is the defensive fuel, especially for shield actions, and it builds on successful blocks.",
          "Focus supports precise and technical actions. In the current code it builds after successful dodges.",
          "Rage is tied to heavier commitments and crit-oriented play. In the current code it builds after crits.",
          "All resources are capped at 100, and consumables or timed effects can also restore or drain them over time.",
        ],
        callouts: [
          { label: "Momentum", value: "+10 on clean hit, +8 on penetration", tone: "strength" },
          { label: "Guard", value: "+12 on block", tone: "armor" },
          { label: "Focus", value: "+10 on dodge", tone: "agility" },
          { label: "Rage", value: "+14 on crit", tone: "rage" },
          { label: "Effect Tick", value: "Can heal HP or drain Guard / Focus each turn", tone: "armor" },
        ],
      },
      {
        id: "example",
        title: "Damage example",
        intro: "This is a simplified example of how the game thinks about one Training Sword hit into a defended chest zone with Leather Vest.",
        bullets: [
          "Start from the sword base profile: 80% slash and 20% pierce, then mix in the zone style profile.",
          "Chest uses the x1.1 zone modifier, so the attack profile grows slightly before mitigation.",
          "If the zone is covered, chest-zone armor, Leather Vest and possible off-hand block all matter.",
          "Then slash and pierce are reduced separately by armor, then penetration, block and crit are checked.",
          "Only the remaining profile becomes final damage.",
        ],
        steps: [
          "1. The sword creates a slash/pierce profile.",
          "2. Chest adds x1.1 damage.",
          "3. Armor mitigates slash and pierce separately.",
          "4. Penetration partly bypasses armor, and block may cut the rest.",
          "5. Crit multiplies the surviving profile, then final damage is summed.",
        ],
        callouts: [
          { label: "Weapon", value: "Training Sword: 80% slash / 20% pierce", tone: "strength" },
          { label: "Zone", value: "Chest: x1.1 damage", tone: "pierce" },
          { label: "Armor", value: "Leather Vest: 12 slash / 6 pierce / 4 blunt / 8 chop", tone: "armor" },
          { label: "Takeaway", value: "Slash-heavy hits work best where slash armor and block are weaker", tone: "strength" },
        ],
      },
      {
        id: "tips",
        title: "Practical tips",
        intro: "If you read the system like a player, these are the main things to remember.",
        bullets: [
          "Without an equipped weapon, you lose the weapon-based skill line.",
          "Do not just stack strong skills. Build a 5-button panel with different resource costs so it stays usable.",
          "Bad defense zone choices sharply reduce your chance to block.",
          "Two-hand weapons give power but remove shield synergy.",
          "Look at the enemy armor profile, not just your raw damage.",
          "Watch the status row above HP. Those are live buffs and debuffs, not cosmetic labels.",
          "Sometimes a consumable in the right round is better than one more basic hit. Regen Potion is now a 5-turn effect, not just a one-shot heal.",
          "The battle log now surfaces healing ticks, effect expiration and full blocks as separate readable outcomes.",
        ],
      },
    ],
  },
};

export const combatRulesContent: Record<Locale, RulePageCopy> = {
  ru: {
    ...rawCombatRulesContent.ru,
    sections: withGeneratedCombatRulesFacts(rawCombatRulesContent.ru.sections, "ru"),
  },
  en: {
    ...rawCombatRulesContent.en,
    sections: withGeneratedCombatRulesFacts(rawCombatRulesContent.en.sections, "en"),
  },
};
