import { zeroCharacterStats } from "@/modules/character";
import {
  zeroArmorProfile,
  zeroCombatBonuses,
  zeroDamageProfile,
  type Item,
} from "@/modules/inventory/model/Item";

export const starterItems: Array<{ item: Item; quantity: number }> = [
  {
    item: {
      id: "training-sword",
      code: "training-sword",
      name: "Training Sword",
      category: "weapon",
      type: "weapon",
      rarity: "common",
      description: "One-hand sword with slash pressure and light penetration.",
      value: 12,
      stackable: false,
      maxStack: 1,
      equip: {
        slot: "mainHand",
        handedness: "one_hand",
        weaponClass: "sword",
      },
      baseDamage: {
        slash: 13,
        pierce: 4,
        blunt: 0,
        chop: 0,
      },
      baseArmor: zeroArmorProfile,
      combatBonuses: {
        ...zeroCombatBonuses,
        critChance: 2,
        armorPenetrationPercent: {
          slash: 8,
          pierce: 14,
          blunt: 0,
          chop: 0,
        },
      },
      skills: [
        {
          id: "training-sword-feint",
          name: "Feint Slash",
          description: "Momentum strike: higher slash damage, crit, and bleed.",
          sourceItemCode: "training-sword",
          resourceType: "momentum",
          cost: 20,
          damageMultiplier: 1.38,
          critChanceBonus: 12,
          armorPenetrationPercentBonus: {
            slash: 22,
            pierce: 10,
            blunt: 0,
            chop: 0,
          },
          effects: [
            {
              id: "feint-slash-bleeding-line",
              name: "Bleeding Line",
              description: "Deals bleed damage at the start of the target's turn.",
              kind: "debuff",
              target: "target",
              trigger: "on_hit",
              durationTurns: 2,
              periodic: {
                damage: 7,
              },
            },
          ],
        },
        {
          id: "training-sword-expose-guard",
          name: "Expose Guard",
          description: "Momentum strike: lowers armor and increases incoming damage.",
          sourceItemCode: "training-sword",
          resourceType: "momentum",
          cost: 18,
          damageMultiplier: 1.12,
          critChanceBonus: 6,
          armorPenetrationPercentBonus: {
            slash: 16,
            pierce: 24,
            blunt: 0,
            chop: 8,
          },
          effects: [
            {
              id: "expose-guard-sundered-plating",
              name: "Sundered Plating",
              description: "Reduces armor and makes the target take more damage.",
              kind: "debuff",
              target: "target",
              trigger: "on_hit",
              durationTurns: 2,
              modifiers: {
                incomingDamagePercent: 8,
                armorFlatBonus: {
                  slash: -5,
                  pierce: -5,
                  blunt: -3,
                  chop: -5,
                },
              },
            },
          ],
        },
      ],
      statBonuses: {
        strength: 2,
        agility: 0,
        rage: 0,
        endurance: 0,
      },
      flatBonuses: {
        strength: 2,
        agility: 0,
        rage: 0,
        endurance: 0,
      },
      percentBonuses: zeroCharacterStats,
    },
    quantity: 1,
  },
  {
    item: {
      id: "training-dagger",
      code: "training-dagger",
      name: "Training Dagger",
      category: "weapon",
      type: "weapon",
      rarity: "common",
      description: "Fast dagger with pierce damage, crit chance, and penetration.",
      value: 11,
      stackable: false,
      maxStack: 1,
      equip: {
        slot: "mainHand",
        handedness: "one_hand",
        weaponClass: "dagger",
      },
      baseDamage: {
        slash: 4,
        pierce: 18,
        blunt: 0,
        chop: 0,
      },
      baseArmor: zeroArmorProfile,
      combatBonuses: {
        ...zeroCombatBonuses,
        critChance: 9,
        critMultiplier: 0.15,
        armorPenetrationPercent: {
          slash: 0,
          pierce: 24,
          blunt: 0,
          chop: 0,
        },
      },
      skills: [
        {
          id: "training-dagger-lunge",
          name: "Piercing Lunge",
          description: "Focus thrust: high pierce crit and penetration that can expose the target for the next finisher.",
          sourceItemCode: "training-dagger",
          resourceType: "focus",
          cost: 16,
          damageMultiplier: 1.42,
          critChanceBonus: 20,
          armorPenetrationPercentBonus: {
            slash: 0,
            pierce: 40,
            blunt: 0,
            chop: 0,
          },
          effects: [
            {
              id: "state-exposed",
              name: "Exposed",
              description: "The target becomes more vulnerable to follow-up damage.",
              kind: "debuff",
              target: "target",
              trigger: "on_hit",
              durationTurns: 2,
              maxStacks: 2,
              modifiers: {
                incomingDamagePercent: 8,
              },
            },
          ],
        },
        {
          id: "training-dagger-ghoststep",
          name: "Ghoststep",
          description: "Focus strike: grants dodge and lowers incoming damage.",
          sourceItemCode: "training-dagger",
          resourceType: "focus",
          cost: 16,
          damageMultiplier: 1,
          critChanceBonus: 10,
          armorPenetrationPercentBonus: {
            slash: 0,
            pierce: 14,
            blunt: 0,
            chop: 0,
          },
          effects: [
            {
              id: "ghoststep-flicker-stance",
              name: "Flicker Stance",
              description: "Grants dodge, outgoing damage, and reduced incoming damage.",
              kind: "buff",
              target: "self",
              trigger: "on_use",
              durationTurns: 3,
              modifiers: {
                dodgeChanceBonus: 18,
                incomingDamagePercent: -14,
                outgoingDamagePercent: 8,
              },
            },
          ],
        },
        {
          id: "training-dagger-heartseeker",
          name: "Heartseeker",
          description: "Focus finisher: heavy crit and anti-armor pierce that spikes into exposed targets.",
          sourceItemCode: "training-dagger",
          resourceType: "focus",
          cost: 24,
          damageMultiplier: 1.72,
          critChanceBonus: 40,
          armorPenetrationPercentBonus: {
            slash: 0,
            pierce: 62,
            blunt: 0,
            chop: 0,
          },
          effects: [
            {
              id: "heartseeker-open-vein",
              name: "Open Vein",
              description: "Target takes more damage for a short time.",
              kind: "debuff",
              target: "target",
              trigger: "on_hit",
              durationTurns: 2,
              modifiers: {
                incomingDamagePercent: 10,
              },
            },
          ],
          stateBonuses: [
            {
              requiredEffectId: "state-exposed",
              damageMultiplierBonus: 0.28,
              critChanceBonus: 14,
              armorPenetrationPercentBonus: {
                slash: 0,
                pierce: 24,
                blunt: 0,
                chop: 0,
              },
            },
          ],
        },
      ],
      statBonuses: {
        strength: 0,
        agility: 1,
        rage: 1,
        endurance: 0,
      },
      flatBonuses: {
        strength: 0,
        agility: 1,
        rage: 1,
        endurance: 0,
      },
      percentBonuses: zeroCharacterStats,
    },
    quantity: 1,
  },
  {
    item: {
      id: "training-mace",
      code: "training-mace",
      name: "Training Mace",
      category: "weapon",
      type: "weapon",
      rarity: "common",
      description: "Blunt weapon that pressures guard and weakens defense.",
      value: 13,
      stackable: false,
      maxStack: 1,
      equip: {
        slot: "mainHand",
        handedness: "one_hand",
        weaponClass: "mace",
      },
      baseDamage: {
        slash: 0,
        pierce: 0,
        blunt: 12,
        chop: 0,
      },
      baseArmor: zeroArmorProfile,
      combatBonuses: {
        ...zeroCombatBonuses,
        blockPower: 4,
        armorPenetrationPercent: {
          slash: 0,
          pierce: 0,
          blunt: 12,
          chop: 0,
        },
      },
      skills: [
        {
          id: "training-mace-crush",
          name: "Crushing Blow",
          description: "Guard smash: stronger blunt damage that spikes against staggered targets.",
          sourceItemCode: "training-mace",
          resourceType: "guard",
          cost: 24,
          damageMultiplier: 1.02,
          critChanceBonus: 0,
          armorPenetrationPercentBonus: {
            slash: 0,
            pierce: 0,
            blunt: 10,
            chop: 0,
          },
          stateBonuses: [
            {
              requiredEffectId: "state-staggered",
              damageMultiplierBonus: 0.18,
              armorPenetrationPercentBonus: {
                slash: 0,
                pierce: 0,
                blunt: 18,
                chop: 0,
              },
            },
          ],
        },
        {
          id: "training-mace-armor-crush",
          name: "Armor Crush",
          description: "Guard smash: staggers the target and weakens their defensive structure.",
          sourceItemCode: "training-mace",
          resourceType: "guard",
          cost: 26,
          damageMultiplier: 0.96,
          critChanceBonus: 0,
          armorPenetrationPercentBonus: {
            slash: 0,
            pierce: 0,
            blunt: 18,
            chop: 0,
          },
          effects: [
            {
              id: "state-staggered",
              name: "Staggered",
              description: "The target has worse block power and dodge on their next exchange.",
              kind: "debuff",
              target: "target",
              trigger: "on_hit",
              durationTurns: 2,
              maxStacks: 2,
              modifiers: {
                blockPowerBonus: -6,
                dodgeChanceBonus: -4,
              },
            },
          ],
        },
      ],
      statBonuses: {
        strength: 1,
        agility: 0,
        rage: 0,
        endurance: 1,
      },
      flatBonuses: {
        strength: 1,
        agility: 0,
        rage: 0,
        endurance: 1,
      },
      percentBonuses: zeroCharacterStats,
    },
    quantity: 1,
  },
  {
    item: {
      id: "sparring-axe",
      code: "sparring-axe",
      name: "Sparring Axe",
      category: "weapon",
      type: "weapon",
      rarity: "common",
      description: "Axe with chop pressure and strong low-line penetration.",
      value: 13,
      stackable: false,
      maxStack: 1,
      equip: {
        slot: "mainHand",
        handedness: "one_hand",
        weaponClass: "axe",
      },
      baseDamage: {
        slash: 2,
        pierce: 0,
        blunt: 0,
        chop: 14,
      },
      baseArmor: zeroArmorProfile,
      combatBonuses: {
        ...zeroCombatBonuses,
        critChance: 2,
        armorPenetrationPercent: {
          slash: 0,
          pierce: 0,
          blunt: 0,
          chop: 20,
        },
      },
      skills: [
        {
          id: "sparring-axe-hook",
          name: "Hook Chop",
          description: "Rage chop: stronger chop pressure that spikes against exposed targets.",
          sourceItemCode: "sparring-axe",
          resourceType: "rage",
          cost: 20,
          damageMultiplier: 1.24,
          critChanceBonus: 6,
          armorPenetrationPercentBonus: {
            slash: 0,
            pierce: 0,
            blunt: 0,
            chop: 28,
          },
          stateBonuses: [
            {
              requiredEffectId: "state-exposed",
              damageMultiplierBonus: 0.22,
              critChanceBonus: 10,
              armorPenetrationPercentBonus: {
                slash: 0,
                pierce: 0,
                blunt: 0,
                chop: 18,
              },
            },
          ],
        },
        {
          id: "sparring-axe-open-flank",
          name: "Open Flank",
          description: "Rage opener: tears the guard line open and exposes the target for follow-up chops.",
          sourceItemCode: "sparring-axe",
          resourceType: "rage",
          cost: 22,
          damageMultiplier: 1.08,
          critChanceBonus: 8,
          armorPenetrationPercentBonus: {
            slash: 0,
            pierce: 0,
            blunt: 0,
            chop: 18,
          },
          effects: [
            {
              id: "state-exposed",
              name: "Exposed",
              description: "The target becomes more vulnerable to follow-up damage.",
              kind: "debuff",
              target: "target",
              trigger: "on_hit",
              durationTurns: 2,
              maxStacks: 2,
              modifiers: {
                incomingDamagePercent: 8,
              },
            },
          ],
        },
      ],
      statBonuses: {
        strength: 1,
        agility: 0,
        rage: 1,
        endurance: 0,
      },
      flatBonuses: {
        strength: 1,
        agility: 0,
        rage: 1,
        endurance: 0,
      },
      percentBonuses: zeroCharacterStats,
    },
    quantity: 1,
  },
  {
    item: {
      id: "oak-shield",
      code: "oak-shield",
      name: "Oak Shield",
      category: "shield",
      type: "shield",
      rarity: "common",
      description: "Shield with block power and strong head-chest coverage.",
      value: 15,
      stackable: false,
      maxStack: 1,
      equip: {
        slot: "offHand",
        handedness: "off_hand_only",
        armorClass: "shield",
      },
      baseDamage: zeroDamageProfile,
      baseArmor: {
        slash: 6,
        pierce: 8,
        blunt: 10,
        chop: 7,
      },
      combatBonuses: {
        ...zeroCombatBonuses,
        blockPower: 8,
        armorFlat: {
          slash: 1,
          pierce: 1,
          blunt: 2,
          chop: 1,
        },
      },
      skills: [
        {
          id: "oak-shield-bash",
          name: "Shield Bash",
          description: "Guard bash: blunt impact that staggers the target and drains their defensive resources.",
          sourceItemCode: "oak-shield",
          resourceType: "guard",
          cost: 22,
          damageMultiplier: 1.02,
          critChanceBonus: 0,
          armorPenetrationPercentBonus: {
            slash: 0,
            pierce: 0,
            blunt: 10,
            chop: 0,
          },
          effects: [
            {
              id: "state-staggered",
              name: "Staggered",
              description: "The target has worse block power and dodge on their next exchange.",
              kind: "debuff",
              target: "target",
              trigger: "on_hit",
              durationTurns: 2,
              maxStacks: 2,
              modifiers: {
                blockPowerBonus: -6,
                dodgeChanceBonus: -4,
              },
            },
            {
              id: "shield-bash-rattled-guard",
              name: "Rattled Guard",
              description: "Drains guard and focus on the target's turn.",
              kind: "debuff",
              target: "target",
              trigger: "on_hit",
              durationTurns: 1,
              periodic: {
                resourceDelta: {
                  guard: -4,
                  focus: -2,
                },
              },
            },
          ],
        },
        {
          id: "oak-shield-second-wind",
          name: "Second Wind",
          description: "Guard recovery: heal and restore guard over time.",
          sourceItemCode: "oak-shield",
          resourceType: "guard",
          cost: 26,
          damageMultiplier: 0.84,
          critChanceBonus: 0,
          armorPenetrationPercentBonus: {
            slash: 0,
            pierce: 0,
            blunt: 6,
            chop: 0,
          },
          effects: [
            {
              id: "second-wind-guarded-recovery",
              name: "Guarded Recovery",
              description: "Restores health and guard for a short time.",
              kind: "buff",
              target: "self",
              trigger: "on_use",
              durationTurns: 2,
              modifiers: {
                incomingDamagePercent: -4,
              },
              periodic: {
                heal: 2,
                resourceDelta: {
                  guard: 1,
                },
              },
            },
          ],
        },
      ],
      statBonuses: {
        strength: 0,
        agility: 0,
        rage: 0,
        endurance: 1,
      },
      flatBonuses: {
        strength: 0,
        agility: 0,
        rage: 0,
        endurance: 1,
      },
      percentBonuses: zeroCharacterStats,
    },
    quantity: 1,
  },
  {
    item: {
      id: "great-training-sword",
      code: "great-training-sword",
      name: "Great Training Sword",
      category: "weapon",
      type: "weapon",
      rarity: "rare",
      description: "Two-hand greatsword with heavy slash damage and penetration.",
      value: 26,
      stackable: false,
      maxStack: 1,
      equip: {
        slot: "mainHand",
        handedness: "two_hand",
        weaponClass: "greatsword",
      },
      baseDamage: {
        slash: 18,
        pierce: 5,
        blunt: 0,
        chop: 0,
      },
      baseArmor: zeroArmorProfile,
      combatBonuses: {
        ...zeroCombatBonuses,
        armorPenetrationPercent: {
          slash: 16,
          pierce: 16,
          blunt: 0,
          chop: 0,
        },
      },
      skills: [
        {
          id: "great-training-sword-cleave",
          name: "Heavy Cleave",
          description: "Rage cleave: heavy slash damage, guard break, and a setup window for the next finisher.",
          sourceItemCode: "great-training-sword",
          resourceType: "rage",
          cost: 24,
          damageMultiplier: 1.5,
          critChanceBonus: 10,
          armorPenetrationPercentBonus: {
            slash: 26,
            pierce: 10,
            blunt: 0,
            chop: 12,
          },
          effects: [
            {
              id: "heavy-cleave-routed-guard",
              name: "Routed Guard",
              description: "Makes the target take more damage and lowers block power.",
              kind: "debuff",
              target: "target",
              trigger: "on_hit",
              durationTurns: 1,
              modifiers: {
                incomingDamagePercent: 8,
                blockPowerBonus: -6,
              },
            },
            {
              id: "state-exposed",
              name: "Exposed",
              description: "The target becomes more vulnerable to follow-up damage.",
              kind: "debuff",
              target: "target",
              trigger: "on_hit",
              durationTurns: 2,
              maxStacks: 2,
              modifiers: {
                incomingDamagePercent: 8,
              },
            },
          ],
        },
        {
          id: "great-training-sword-execution-arc",
          name: "Execution Arc",
          description: "Rage finisher: heavy damage that spikes against exposed targets.",
          sourceItemCode: "great-training-sword",
          resourceType: "rage",
          cost: 30,
          damageMultiplier: 1.9,
          critChanceBonus: 14,
          armorPenetrationPercentBonus: {
            slash: 32,
            pierce: 12,
            blunt: 0,
            chop: 22,
          },
          stateBonuses: [
            {
              requiredEffectId: "state-exposed",
              damageMultiplierBonus: 0.34,
              critChanceBonus: 14,
              armorPenetrationPercentBonus: {
                slash: 16,
                pierce: 0,
                blunt: 0,
                chop: 16,
              },
            },
          ],
        },
      ],
      statBonuses: {
        strength: 3,
        agility: -1,
        rage: 0,
        endurance: 0,
      },
      flatBonuses: {
        strength: 3,
        agility: -1,
        rage: 0,
        endurance: 0,
      },
      percentBonuses: zeroCharacterStats,
    },
    quantity: 1,
  },
  {
    item: {
      id: "leather-cap",
      code: "leather-cap",
      name: "Leather Cap",
      category: "armor",
      type: "helmet",
      rarity: "common",
      description: "Light helmet with head protection and a dodge skill.",
      value: 9,
      stackable: false,
      maxStack: 1,
      equip: {
        slot: "helmet",
        armorClass: "helmet",
      },
      baseDamage: zeroDamageProfile,
      baseArmor: {
        slash: 5,
        pierce: 4,
        blunt: 7,
        chop: 4,
      },
      combatBonuses: {
        ...zeroCombatBonuses,
        blockChance: 2,
      },
      skills: [
        {
          id: "leather-cap-head-slip",
          name: "Head Slip",
          description: "Focus slip: grants a short dodge buff.",
          sourceItemCode: "leather-cap",
          resourceType: "focus",
          cost: 14,
          damageMultiplier: 1.1,
          critChanceBonus: 6,
          armorPenetrationPercentBonus: {
            slash: 6,
            pierce: 12,
            blunt: 0,
            chop: 0,
          },
          effects: [
            {
              id: "head-slip-evasive-window",
              name: "Evasive Window",
              description: "Grants dodge for the next exchange.",
              kind: "buff",
              target: "self",
              trigger: "on_use",
              durationTurns: 1,
              modifiers: {
                dodgeChanceBonus: 10,
              },
            },
          ],
        },
      ],
      statBonuses: {
        strength: 0,
        agility: 0,
        rage: 0,
        endurance: 1,
      },
      flatBonuses: {
        strength: 0,
        agility: 0,
        rage: 0,
        endurance: 1,
      },
      percentBonuses: zeroCharacterStats,
    },
    quantity: 1,
  },
  {
    item: {
      id: "leather-vest",
      code: "leather-vest",
      name: "Leather Vest",
      category: "armor",
      type: "armor",
      rarity: "common",
      description: "Light armor with slash-chop protection and a defensive counter.",
      value: 15,
      stackable: false,
      maxStack: 1,
      equip: {
        slot: "armor",
        armorClass: "armor",
      },
      baseDamage: zeroDamageProfile,
      baseArmor: {
        slash: 10,
        pierce: 5,
        blunt: 3,
        chop: 6,
      },
      combatBonuses: {
        ...zeroCombatBonuses,
        armorFlat: {
          slash: 3,
          pierce: 1,
          blunt: 1,
          chop: 2,
        },
      },
      skills: [
        {
          id: "leather-vest-iron-brace",
          name: "Iron Brace",
          description: "Guard brace: attack and short incoming-damage reduction that hits harder into staggered targets.",
          sourceItemCode: "leather-vest",
          resourceType: "guard",
          cost: 14,
          damageMultiplier: 1.08,
          critChanceBonus: 0,
          armorPenetrationPercentBonus: {
            slash: 0,
            pierce: 0,
            blunt: 14,
            chop: 10,
          },
          effects: [
            {
              id: "iron-brace-braced-core",
              name: "Braced Core",
              description: "Reduces incoming damage for a short time.",
              kind: "buff",
              target: "self",
              trigger: "on_use",
              durationTurns: 1,
              modifiers: {
                incomingDamagePercent: -12,
              },
            },
          ],
          stateBonuses: [
            {
              requiredEffectId: "state-staggered",
              damageMultiplierBonus: 0.14,
              armorPenetrationPercentBonus: {
                slash: 0,
                pierce: 0,
                blunt: 14,
                chop: 12,
              },
            },
          ],
        },
      ],
      statBonuses: {
        strength: 0,
        agility: 0,
        rage: 0,
        endurance: 2,
      },
      flatBonuses: {
        strength: 0,
        agility: 0,
        rage: 0,
        endurance: 2,
      },
      percentBonuses: zeroCharacterStats,
    },
    quantity: 1,
  },
  {
    item: {
      id: "chain-jacket",
      code: "chain-jacket",
      name: "Chain Jacket",
      category: "armor",
      type: "armor",
      rarity: "rare",
      description: "Heavy armor with better pierce and blunt protection.",
      value: 24,
      stackable: false,
      maxStack: 1,
      equip: {
        slot: "armor",
        armorClass: "armor",
      },
      baseDamage: zeroDamageProfile,
      baseArmor: {
        slash: 8,
        pierce: 10,
        blunt: 8,
        chop: 6,
      },
      combatBonuses: {
        ...zeroCombatBonuses,
        armorFlat: {
          slash: 1,
          pierce: 3,
          blunt: 3,
          chop: 1,
        },
      },
      skills: [
        {
          id: "chain-jacket-body-check",
          name: "Body Check",
          description: "Guard rush: blunt pressure through armor that spikes into staggered targets.",
          sourceItemCode: "chain-jacket",
          resourceType: "guard",
          cost: 18,
          damageMultiplier: 1.04,
          critChanceBonus: 0,
          armorPenetrationPercentBonus: {
            slash: 10,
            pierce: 0,
            blunt: 18,
            chop: 0,
          },
          stateBonuses: [
            {
              requiredEffectId: "state-staggered",
              damageMultiplierBonus: 0.2,
              armorPenetrationPercentBonus: {
                slash: 0,
                pierce: 0,
                blunt: 20,
                chop: 0,
              },
            },
          ],
        },
      ],
      statBonuses: {
        strength: 0,
        agility: 0,
        rage: 0,
        endurance: 3,
      },
      flatBonuses: {
        strength: 0,
        agility: 0,
        rage: 0,
        endurance: 3,
      },
      percentBonuses: zeroCharacterStats,
    },
    quantity: 1,
  },
  {
    item: {
      id: "braced-gloves",
      code: "braced-gloves",
      name: "Braced Gloves",
      category: "armor",
      type: "gloves",
      rarity: "common",
      description: "Gloves that improve block power and parry follow-ups.",
      value: 8,
      stackable: false,
      maxStack: 1,
      equip: {
        slot: "gloves",
        armorClass: "gloves",
      },
      baseDamage: zeroDamageProfile,
      baseArmor: {
        slash: 3,
        pierce: 2,
        blunt: 2,
        chop: 2,
      },
      combatBonuses: {
        ...zeroCombatBonuses,
        blockPower: 4,
      },
      skills: [
        {
          id: "braced-gloves-parry-riposte",
          name: "Parry Riposte",
          description: "Guard riposte: grants block power and crit chance, then punishes staggered targets much harder.",
          sourceItemCode: "braced-gloves",
          resourceType: "guard",
          cost: 15,
          damageMultiplier: 1.14,
          critChanceBonus: 4,
          armorPenetrationPercentBonus: {
            slash: 12,
            pierce: 8,
            blunt: 0,
            chop: 0,
          },
          effects: [
            {
              id: "parry-riposte-readied-guard",
              name: "Readied Guard",
              description: "Grants block power and crit chance for a short time.",
              kind: "buff",
              target: "self",
              trigger: "on_use",
              durationTurns: 1,
              modifiers: {
                blockPowerBonus: 10,
                critChanceBonus: 4,
              },
            },
          ],
          stateBonuses: [
            {
              requiredEffectId: "state-staggered",
              damageMultiplierBonus: 0.18,
              critChanceBonus: 8,
              armorPenetrationPercentBonus: {
                slash: 12,
                pierce: 8,
                blunt: 0,
                chop: 0,
              },
            },
          ],
        },
      ],
      statBonuses: {
        strength: 0,
        agility: 0,
        rage: 0,
        endurance: 1,
      },
      flatBonuses: {
        strength: 0,
        agility: 0,
        rage: 0,
        endurance: 1,
      },
      percentBonuses: zeroCharacterStats,
    },
    quantity: 1,
  },
  {
    item: {
      id: "trail-boots",
      code: "trail-boots",
      name: "Trail Boots",
      category: "armor",
      type: "boots",
      rarity: "common",
      description: "Boots with dodge and low-line pressure.",
      value: 8,
      stackable: false,
      maxStack: 1,
      equip: {
        slot: "boots",
        armorClass: "boots",
      },
      baseDamage: zeroDamageProfile,
      baseArmor: {
        slash: 2,
        pierce: 1,
        blunt: 3,
        chop: 3,
      },
      combatBonuses: {
        ...zeroCombatBonuses,
        dodgeChance: 3,
      },
      skills: [
        {
          id: "trail-boots-low-feint",
          name: "Low Feint",
          description: "Momentum step: punishes low coverage.",
          sourceItemCode: "trail-boots",
          resourceType: "momentum",
          cost: 14,
          damageMultiplier: 1.12,
          critChanceBonus: 0,
          armorPenetrationPercentBonus: {
            slash: 4,
            pierce: 0,
            blunt: 0,
            chop: 16,
          },
        },
      ],
      statBonuses: {
        strength: 0,
        agility: 1,
        rage: 0,
        endurance: 0,
      },
      flatBonuses: {
        strength: 0,
        agility: 1,
        rage: 0,
        endurance: 0,
      },
      percentBonuses: zeroCharacterStats,
    },
    quantity: 1,
  },
  {
    item: {
      id: "duelist-charm",
      code: "duelist-charm",
      name: "Duelist Charm",
      category: "accessory",
      type: "accessory",
      rarity: "rare",
      description: "Charm with crit, dodge, and precision support.",
      value: 18,
      stackable: false,
      maxStack: 1,
      equip: {
        slot: "accessory",
        armorClass: "accessory",
      },
      baseDamage: zeroDamageProfile,
      baseArmor: {
        slash: 1,
        pierce: 1,
        blunt: 0,
        chop: 0,
      },
      combatBonuses: {
        ...zeroCombatBonuses,
        critChance: 3,
        dodgeChance: 3,
      },
      skills: [
        {
          id: "duelist-charm-opening-sense",
          name: "Opening Sense",
          description: "Focus read: precise pierce pressure that exposes the target for finishers.",
          sourceItemCode: "duelist-charm",
          resourceType: "focus",
          cost: 15,
          damageMultiplier: 1.16,
          critChanceBonus: 10,
          armorPenetrationPercentBonus: {
            slash: 8,
            pierce: 22,
            blunt: 0,
            chop: 0,
          },
          effects: [
            {
              id: "state-exposed",
              name: "Exposed",
              description: "The target becomes more vulnerable to follow-up damage.",
              kind: "debuff",
              target: "target",
              trigger: "on_hit",
              durationTurns: 2,
              maxStacks: 2,
              modifiers: {
                incomingDamagePercent: 8,
              },
            },
          ],
        },
      ],
      statBonuses: {
        strength: 0,
        agility: 1,
        rage: 1,
        endurance: 0,
      },
      flatBonuses: {
        strength: 0,
        agility: 1,
        rage: 1,
        endurance: 0,
      },
      percentBonuses: zeroCharacterStats,
    },
    quantity: 1,
  },
  {
    item: {
      id: "arena-earring",
      code: "arena-earring",
      name: "Arena Earring",
      category: "accessory",
      type: "accessory",
      rarity: "rare",
      description: "Earring with crit support and finishing pressure.",
      value: 19,
      stackable: false,
      maxStack: 1,
      equip: {
        slot: "accessory",
        armorClass: "accessory",
      },
      baseDamage: zeroDamageProfile,
      baseArmor: {
        slash: 0,
        pierce: 1,
        blunt: 0,
        chop: 0,
      },
      combatBonuses: {
        ...zeroCombatBonuses,
        critChance: 5,
        dodgeChance: 2,
      },
      skills: [
        {
          id: "arena-earring-killer-focus",
          name: "Killer Focus",
          description: "Focus spike: boosts damage and crit, then cuts much harder into exposed targets.",
          sourceItemCode: "arena-earring",
          resourceType: "focus",
          cost: 10,
          damageMultiplier: 1.46,
          critChanceBonus: 28,
          armorPenetrationPercentBonus: {
            slash: 16,
            pierce: 38,
            blunt: 0,
            chop: 0,
          },
          effects: [
            {
              id: "killer-focus-finish-window",
              name: "Finish Window",
              description: "Grants crit chance and outgoing damage for a short time.",
              kind: "buff",
              target: "self",
              trigger: "on_use",
              durationTurns: 2,
              modifiers: {
                critChanceBonus: 14,
                outgoingDamagePercent: 12,
              },
            },
          ],
          stateBonuses: [
            {
              requiredEffectId: "state-exposed",
              damageMultiplierBonus: 0.3,
              critChanceBonus: 12,
              armorPenetrationPercentBonus: {
                slash: 10,
                pierce: 22,
                blunt: 0,
                chop: 0,
              },
            },
          ],
        },
      ],
      statBonuses: {
        strength: 0,
        agility: 1,
        rage: 1,
        endurance: 0,
      },
      flatBonuses: {
        strength: 0,
        agility: 1,
        rage: 1,
        endurance: 0,
      },
      percentBonuses: zeroCharacterStats,
    },
    quantity: 1,
  },
  {
    item: {
      id: "war-medallion",
      code: "war-medallion",
      name: "War Medallion",
      category: "accessory",
      type: "accessory",
      rarity: "rare",
      description: "Medallion with rage scaling and finisher support.",
      value: 20,
      stackable: false,
      maxStack: 1,
      equip: {
        slot: "accessory",
        armorClass: "accessory",
      },
      baseDamage: zeroDamageProfile,
      baseArmor: {
        slash: 1,
        pierce: 0,
        blunt: 1,
        chop: 0,
      },
      combatBonuses: {
        ...zeroCombatBonuses,
        critChance: 2,
        critMultiplier: 0.18,
      },
      skills: [
        {
          id: "war-medallion-finisher",
          name: "Execution Mark",
          description: "Rage mark: crit pressure that exposes the target for heavier finishers.",
          sourceItemCode: "war-medallion",
          resourceType: "rage",
          cost: 14,
          damageMultiplier: 1.2,
          critChanceBonus: 16,
          armorPenetrationPercentBonus: {
            slash: 16,
            pierce: 0,
            blunt: 10,
            chop: 16,
          },
          effects: [
            {
              id: "state-exposed",
              name: "Exposed",
              description: "The target becomes more vulnerable to follow-up damage.",
              kind: "debuff",
              target: "target",
              trigger: "on_hit",
              durationTurns: 2,
              maxStacks: 2,
              modifiers: {
                incomingDamagePercent: 8,
              },
            },
          ],
        },
      ],
      statBonuses: {
        strength: 0,
        agility: 0,
        rage: 2,
        endurance: 0,
      },
      flatBonuses: {
        strength: 0,
        agility: 0,
        rage: 2,
        endurance: 0,
      },
      percentBonuses: zeroCharacterStats,
    },
    quantity: 1,
  },
  {
    item: {
      id: "small-potion",
      code: "small-potion",
      name: "Small Potion",
      category: "consumable",
      type: "consumable",
      rarity: "common",
      description: "Small heal that restores focus.",
      value: 8,
      stackable: true,
      maxStack: 5,
      equip: null,
      consumableEffect: {
        usageMode: "replace_attack",
        heal: 24,
        resourceRestore: {
          focus: 8,
        },
      },
      baseDamage: zeroDamageProfile,
      baseArmor: zeroArmorProfile,
      combatBonuses: zeroCombatBonuses,
      statBonuses: zeroCharacterStats,
      flatBonuses: zeroCharacterStats,
      percentBonuses: zeroCharacterStats,
    },
    quantity: 2,
  },
  {
    item: {
      id: "bandage",
      code: "bandage",
      name: "Bandage",
      category: "consumable",
      type: "consumable",
      rarity: "common",
      description: "Heal-over-hit consumable that restores guard.",
      value: 3,
      stackable: true,
      maxStack: 10,
      equip: null,
      consumableEffect: {
        usageMode: "with_attack",
        heal: 12,
        resourceRestore: {
          guard: 6,
        },
      },
      baseDamage: zeroDamageProfile,
      baseArmor: zeroArmorProfile,
      combatBonuses: zeroCombatBonuses,
      statBonuses: zeroCharacterStats,
      flatBonuses: zeroCharacterStats,
      percentBonuses: zeroCharacterStats,
    },
    quantity: 3,
  },
  {
    item: {
      id: "regen-potion",
      code: "regen-potion",
      name: "Regen Potion",
      category: "consumable",
      type: "consumable",
      rarity: "rare",
      description: "Consumable that grants regeneration over time.",
      value: 14,
      stackable: true,
      maxStack: 3,
      equip: null,
      consumableEffect: {
        usageMode: "replace_attack",
        heal: 0,
        resourceRestore: {},
        effects: [
          {
            id: "regen-potion-regeneration",
            name: "Regeneration",
            description: "Restores health at the start of each turn.",
            kind: "buff",
            target: "self",
            trigger: "on_use",
            durationTurns: 3,
            periodic: {
              heal: 4,
            },
          },
        ],
      },
      baseDamage: zeroDamageProfile,
      baseArmor: zeroArmorProfile,
      combatBonuses: zeroCombatBonuses,
      statBonuses: zeroCharacterStats,
      flatBonuses: zeroCharacterStats,
      percentBonuses: zeroCharacterStats,
    },
    quantity: 1,
  },
  {
    item: {
      id: "arena-token",
      code: "arena-token",
      name: "Arena Token",
      category: "material",
      type: "material",
      rarity: "rare",
      description: "Arena material for future reward systems.",
      value: 5,
      stackable: true,
      maxStack: 20,
      equip: null,
      consumableEffect: null,
      baseDamage: zeroDamageProfile,
      baseArmor: zeroArmorProfile,
      combatBonuses: zeroCombatBonuses,
      statBonuses: zeroCharacterStats,
      flatBonuses: zeroCharacterStats,
      percentBonuses: zeroCharacterStats,
    },
    quantity: 5,
  },
] as const;
